//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.SSO.Client.AuthTokenService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSOToken", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SSOToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        private System.DateTime AuthTimeField;
        
        private int TimeOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Domain.SSO.Client.AuthTokenService.SSOUser UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime AuthTime {
            get {
                return this.AuthTimeField;
            }
            set {
                if ((this.AuthTimeField.Equals(value) != true)) {
                    this.AuthTimeField = value;
                    this.RaisePropertyChanged("AuthTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TimeOut {
            get {
                return this.TimeOutField;
            }
            set {
                if ((this.TimeOutField.Equals(value) != true)) {
                    this.TimeOutField = value;
                    this.RaisePropertyChanged("TimeOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Domain.SSO.Client.AuthTokenService.SSOUser User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIDField, value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSOUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SSOUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthTokenService.AuthTokenServiceSoap")]
    public interface AuthTokenServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 tokenID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateToken", ReplyAction="*")]
        Domain.SSO.Client.AuthTokenService.ValidateTokenResponse ValidateToken(Domain.SSO.Client.AuthTokenService.ValidateTokenRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 tokenID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeepToken", ReplyAction="*")]
        Domain.SSO.Client.AuthTokenService.KeepTokenResponse KeepToken(Domain.SSO.Client.AuthTokenService.KeepTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateToken", Namespace="http://tempuri.org/", Order=0)]
        public Domain.SSO.Client.AuthTokenService.ValidateTokenRequestBody Body;
        
        public ValidateTokenRequest() {
        }
        
        public ValidateTokenRequest(Domain.SSO.Client.AuthTokenService.ValidateTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tokenID;
        
        public ValidateTokenRequestBody() {
        }
        
        public ValidateTokenRequestBody(string tokenID) {
            this.tokenID = tokenID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Domain.SSO.Client.AuthTokenService.ValidateTokenResponseBody Body;
        
        public ValidateTokenResponse() {
        }
        
        public ValidateTokenResponse(Domain.SSO.Client.AuthTokenService.ValidateTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Domain.SSO.Client.AuthTokenService.SSOToken ValidateTokenResult;
        
        public ValidateTokenResponseBody() {
        }
        
        public ValidateTokenResponseBody(Domain.SSO.Client.AuthTokenService.SSOToken ValidateTokenResult) {
            this.ValidateTokenResult = ValidateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepToken", Namespace="http://tempuri.org/", Order=0)]
        public Domain.SSO.Client.AuthTokenService.KeepTokenRequestBody Body;
        
        public KeepTokenRequest() {
        }
        
        public KeepTokenRequest(Domain.SSO.Client.AuthTokenService.KeepTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeepTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tokenID;
        
        public KeepTokenRequestBody() {
        }
        
        public KeepTokenRequestBody(string tokenID) {
            this.tokenID = tokenID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Domain.SSO.Client.AuthTokenService.KeepTokenResponseBody Body;
        
        public KeepTokenResponse() {
        }
        
        public KeepTokenResponse(Domain.SSO.Client.AuthTokenService.KeepTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeepTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KeepTokenResult;
        
        public KeepTokenResponseBody() {
        }
        
        public KeepTokenResponseBody(bool KeepTokenResult) {
            this.KeepTokenResult = KeepTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthTokenServiceSoapChannel : Domain.SSO.Client.AuthTokenService.AuthTokenServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthTokenServiceSoapClient : System.ServiceModel.ClientBase<Domain.SSO.Client.AuthTokenService.AuthTokenServiceSoap>, Domain.SSO.Client.AuthTokenService.AuthTokenServiceSoap {
        
        public AuthTokenServiceSoapClient() {
        }
        
        public AuthTokenServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthTokenServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthTokenServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthTokenServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Domain.SSO.Client.AuthTokenService.ValidateTokenResponse Domain.SSO.Client.AuthTokenService.AuthTokenServiceSoap.ValidateToken(Domain.SSO.Client.AuthTokenService.ValidateTokenRequest request) {
            return base.Channel.ValidateToken(request);
        }
        
        public Domain.SSO.Client.AuthTokenService.SSOToken ValidateToken(string tokenID) {
            Domain.SSO.Client.AuthTokenService.ValidateTokenRequest inValue = new Domain.SSO.Client.AuthTokenService.ValidateTokenRequest();
            inValue.Body = new Domain.SSO.Client.AuthTokenService.ValidateTokenRequestBody();
            inValue.Body.tokenID = tokenID;
            Domain.SSO.Client.AuthTokenService.ValidateTokenResponse retVal = ((Domain.SSO.Client.AuthTokenService.AuthTokenServiceSoap)(this)).ValidateToken(inValue);
            return retVal.Body.ValidateTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Domain.SSO.Client.AuthTokenService.KeepTokenResponse Domain.SSO.Client.AuthTokenService.AuthTokenServiceSoap.KeepToken(Domain.SSO.Client.AuthTokenService.KeepTokenRequest request) {
            return base.Channel.KeepToken(request);
        }
        
        public bool KeepToken(string tokenID) {
            Domain.SSO.Client.AuthTokenService.KeepTokenRequest inValue = new Domain.SSO.Client.AuthTokenService.KeepTokenRequest();
            inValue.Body = new Domain.SSO.Client.AuthTokenService.KeepTokenRequestBody();
            inValue.Body.tokenID = tokenID;
            Domain.SSO.Client.AuthTokenService.KeepTokenResponse retVal = ((Domain.SSO.Client.AuthTokenService.AuthTokenServiceSoap)(this)).KeepToken(inValue);
            return retVal.Body.KeepTokenResult;
        }
    }
}
